#!/usr/bin/env bash
# Turn a folder of geotagged photos into a trip fixture the render tests can use.
#
#   ./Tools/exif-to-fixture.sh ~/Pictures/iceland-2024 iceland "Iceland — ring road"
#     → Tests/Fixtures/trips/iceland.json
#
# Why this exists: the §6 gate is three real trips, and the films are worth
# looking at long before an iPhone is in the loop. Dumping place+time out of the
# photos gives the exact input `ImportService` sees on device — same clustering,
# same legs, same routing — with the image bytes left where they are.
#
# Uses `mdls` (Spotlight), which is built into macOS, so there is nothing to
# install. Photos must be in a Spotlight-indexed location: ~/Pictures is, an
# external volume with indexing off is not. Falls back to `exiftool` if present,
# which is more reliable for files Spotlight has not got to yet.
#
# Only place and time are read. No image data is copied anywhere.
set -euo pipefail

FOLDER="${1:?usage: exif-to-fixture.sh <photo-folder> <fixture-name> [title]}"
NAME="${2:?missing fixture name, e.g. iceland}"
TITLE="${3:-$NAME}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_DIR/Tests/Fixtures/trips/${NAME}.json"

[ -d "$FOLDER" ] || { echo "no such folder: $FOLDER" >&2; exit 1; }

TSV="$(mktemp)"
trap 'rm -f "$TSV"' EXIT

if command -v exiftool >/dev/null 2>&1; then
  echo "· reading with exiftool"
  exiftool -q -q -n -r \
    -p '$FileName	$GPSLatitude	$GPSLongitude	${DateTimeOriginal#;DateFmt("%s")}' \
    -ext jpg -ext jpeg -ext heic -ext png -ext dng \
    "$FOLDER" > "$TSV" 2>/dev/null || true
else
  echo "· reading with mdls (install exiftool for better coverage)"
  find "$FOLDER" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.heic' \
       -o -iname '*.png' -o -iname '*.dng' \) -print0 |
  while IFS= read -r -d '' file; do
    python3 - "$file" <<'PY' >> "$TSV" || true
import subprocess, sys, datetime, os
path = sys.argv[1]
keys = ["kMDItemLatitude", "kMDItemLongitude", "kMDItemContentCreationDate"]
out = subprocess.run(["mdls", "-raw", "-name", keys[0], "-name", keys[1],
                      "-name", keys[2], path], capture_output=True, text=True).stdout
lat, lon, when = (out.split("\0") + ["", "", ""])[:3]
if lat in ("", "(null)") or lon in ("", "(null)"):
    sys.exit(0)
try:
    stamp = datetime.datetime.strptime(when.strip(), "%Y-%m-%d %H:%M:%S %z").timestamp()
except ValueError:
    stamp = os.path.getmtime(path)
print(f"{os.path.basename(path)}\t{lat}\t{lon}\t{int(stamp)}")
PY
  done
fi

python3 - "$TSV" "$OUT" "$TITLE" "$FOLDER" <<'PY'
import json, sys, os

tsv, out, title, folder = sys.argv[1:5]
rows = []
for line in open(tsv):
    parts = line.rstrip("\n").split("\t")
    if len(parts) != 4:
        continue
    name, lat, lon, stamp = parts
    try:
        rows.append((name, float(lat), float(lon), float(stamp)))
    except ValueError:
        continue

if not rows:
    sys.exit("no geotagged photos found — check the folder is Spotlight-indexed, "
             "or install exiftool (brew install exiftool)")

rows.sort(key=lambda r: r[3])
start = rows[0][3]
photos = [
    {"id": name, "t": round(stamp - start, 1), "lat": round(lat, 6), "lon": round(lon, 6)}
    for name, lat, lon, stamp in rows
]

lats = [p["lat"] for p in photos]
lons = [p["lon"] for p in photos]
os.makedirs(os.path.dirname(out), exist_ok=True)
json.dump({
    "_comment": f"Generated by Tools/exif-to-fixture.sh from {folder}. "
                "Place and time only — no image data.",
    "title": title,
    "photos": photos,
}, open(out, "w"), ensure_ascii=False, indent=2)
open(out, "a").write("\n")

span_h = (rows[-1][3] - start) / 3600
print(f"\nWrote {out}")
print(f"  {len(photos)} geotagged photos over {span_h:.1f} h")
print(f"  bbox {min(lons):.4f},{min(lats):.4f},{max(lons):.4f},{max(lats):.4f}  (W,S,E,N)")
print("\nCheck a region covers it before rendering:")
print(f"  ./Tools/pmtiles-bounds.sh <region>.pmtiles "
      f"{min(lons):.4f},{min(lats):.4f},{max(lons):.4f},{max(lats):.4f}")
PY
